services:
    app:
        build: .
        container_name: python-server
        command: uvicorn src.main:app --host 0.0.0.0 --port 80 --reload
        ports:
            - 80:80
        volumes:
            - .:/code
        depends_on:
            - redis
    redis:
        image: redis:alpine
        
# build: . - specify that we want to build from the local Dockerfile
# to run - we need to just run 1 command: docker compose up

# adding redis as a database or as a cache
# https://hub.docker.com/_/redis
# depends_on  -> meaning starting will finish only  after mounting all images

